package com.mycompany.gestion_alumnos.GUI;

import com.mycompany.gestion_alumnos.LOGICA.Controladora;
import com.mycompany.gestion_alumnos.LOGICA.Estudiante;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JTable;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;

/**
 *
 * @author Frame-Code
 */
public class ListadoEstudiantesAula extends javax.swing.JPanel implements Mensajes, ModeloTabla {

    private Controladora control;
    private Long idAula;
    private ConsultarEstudiantes consultarEstudiantes;
    private Principal principal;
    private VerEditarEstudiante verEditarEstudiante;

    public ListadoEstudiantesAula() {
        initComponents();
    }

    public ListadoEstudiantesAula(Controladora control, Long idAula, ConsultarEstudiantes consultarEstudiantes, Principal principal) {
        this.control = control;
        this.idAula = idAula;
        this.consultarEstudiantes = consultarEstudiantes;
        this.principal = principal;
        this.initComponents();
        if (!control.leerListEstudiantes().isEmpty()) {
            this.cargarTablaEstudiantes();
            this.cargarNombre();
            this.cargarEstadoMatricula();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblAula = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtCedulaBusqueda = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEstudianteEncontrado = new javax.swing.JTable();
        lblMatricula2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEstudiantes = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        btnRegresar = new javax.swing.JButton();
        btnEliminarEstudiante = new javax.swing.JButton();
        btnAnularMatriculas = new javax.swing.JButton();
        btnVerEditarEstudiante = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(196, 196, 196));
        setPreferredSize(new java.awt.Dimension(761, 657));

        jPanel1.setBackground(new java.awt.Color(196, 196, 196));
        jPanel1.setPreferredSize(new java.awt.Dimension(755, 657));

        lblAula.setFont(new java.awt.Font("Waree", 1, 16)); // NOI18N
        lblAula.setForeground(new java.awt.Color(23, 23, 23));
        lblAula.setText("Aula");

        jLabel17.setForeground(new java.awt.Color(99, 99, 99));
        jLabel17.setText("________________________________________________Buscar estudiante _______________________________________________");

        jPanel2.setBackground(new java.awt.Color(180, 180, 180));

        txtCedulaBusqueda.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(64, 64, 64), 1, true));
        txtCedulaBusqueda.setOpaque(false);

        btnBuscar.setBackground(new java.awt.Color(63, 72, 100));
        btnBuscar.setFont(new java.awt.Font("Waree", 1, 12)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar ");
        btnBuscar.setBorder(null);
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuscarMouseExited(evt);
            }
        });
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Waree", 1, 8)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(99, 99, 99));
        jLabel14.setText("Escribe la cedula del estudiante");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtCedulaBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCedulaBusqueda)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14))
        );

        jPanel3.setBackground(new java.awt.Color(180, 180, 180));

        tblEstudianteEncontrado.setBackground(new java.awt.Color(180, 180, 180));
        tblEstudianteEncontrado.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(23, 23, 23), 1, true));
        tblEstudianteEncontrado.setFont(new java.awt.Font("Waree", 0, 12)); // NOI18N
        tblEstudianteEncontrado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "CÉDULA", "NOMBRES", "EDAD", "ESTADO_MATRICULA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblEstudianteEncontrado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEstudianteEncontradoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEstudianteEncontrado);

        lblMatricula2.setFont(new java.awt.Font("Waree", 1, 12)); // NOI18N
        lblMatricula2.setForeground(new java.awt.Color(71, 71, 71));
        lblMatricula2.setText("Busca un estudiante para comenzar...");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblMatricula2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMatricula2)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(180, 180, 180));

        tblEstudiantes.setBackground(new java.awt.Color(180, 180, 180));
        tblEstudiantes.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(23, 23, 23), 1, true));
        tblEstudiantes.setFont(new java.awt.Font("Waree", 0, 12)); // NOI18N
        tblEstudiantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblEstudiantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEstudiantesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblEstudiantes);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(180, 180, 180));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel6MouseEntered(evt);
            }
        });

        btnRegresar.setBackground(new java.awt.Color(63, 72, 100));
        btnRegresar.setFont(new java.awt.Font("Waree", 1, 12)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("<-- Regresar");
        btnRegresar.setBorder(null);
        btnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegresarMouseExited(evt);
            }
        });
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        btnEliminarEstudiante.setBackground(new java.awt.Color(165, 80, 80));
        btnEliminarEstudiante.setFont(new java.awt.Font("Waree", 1, 12)); // NOI18N
        btnEliminarEstudiante.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarEstudiante.setText("Eliminar estudiante");
        btnEliminarEstudiante.setBorder(null);
        btnEliminarEstudiante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEliminarEstudianteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminarEstudianteMouseExited(evt);
            }
        });
        btnEliminarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarEstudianteActionPerformed(evt);
            }
        });

        btnAnularMatriculas.setBackground(new java.awt.Color(165, 80, 80));
        btnAnularMatriculas.setFont(new java.awt.Font("Waree", 1, 12)); // NOI18N
        btnAnularMatriculas.setForeground(new java.awt.Color(255, 255, 255));
        btnAnularMatriculas.setText("Anular todas las matriculas");
        btnAnularMatriculas.setBorder(null);
        btnAnularMatriculas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAnularMatriculasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAnularMatriculasMouseExited(evt);
            }
        });
        btnAnularMatriculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnularMatriculasActionPerformed(evt);
            }
        });

        btnVerEditarEstudiante.setBackground(new java.awt.Color(63, 72, 100));
        btnVerEditarEstudiante.setFont(new java.awt.Font("Waree", 1, 12)); // NOI18N
        btnVerEditarEstudiante.setForeground(new java.awt.Color(255, 255, 255));
        btnVerEditarEstudiante.setText("Ver/Editar informacion detallada del estudiante ");
        btnVerEditarEstudiante.setBorder(null);
        btnVerEditarEstudiante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVerEditarEstudianteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVerEditarEstudianteMouseExited(evt);
            }
        });
        btnVerEditarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerEditarEstudianteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVerEditarEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAnularMatriculas, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVerEditarEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAnularMatriculas, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel18.setForeground(new java.awt.Color(99, 99, 99));
        jLabel18.setText("______________________________________________Todos los estudiantes_____________________________________________");

        jLabel2.setFont(new java.awt.Font("Waree", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(23, 23, 23));
        jLabel2.setText("Consultar Estudiantes");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblAula, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel17)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAula)
                    .addComponent(jLabel2))
                .addGap(2, 2, 2)
                .addComponent(jLabel17)
                .addGap(12, 12, 12)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        if (!control.obtenerListaEstudiantesAula(idAula).isEmpty()) {
            if (isNumber(txtCedulaBusqueda.getText())) {
                Long idEstudianteBusqueda = Long.valueOf(txtCedulaBusqueda.getText());
                boolean isRegistered = true;
                List<Estudiante> estudianteBusqueda = new ArrayList<>();
                for (Estudiante estudiante : control.obtenerListaEstudiantesAula(idAula)) {
                    if (estudiante.getId().equals(idEstudianteBusqueda)) {
                        isRegistered = true;
                        break;
                    } else {
                        isRegistered = false;
                    }
                }

                if (isRegistered) {
                    estudianteBusqueda.add(control.leerEstudiante(idEstudianteBusqueda));
                    tblEstudianteEncontrado.setModel(obtenerModeloTablaEstudiantes(new String[]{"CÉDULA", "NOMBRES", "EDAD", "ESTADO_MATRÍCULA"}, estudianteBusqueda));
                    tblEstudianteEncontrado.setRowHeight(20);
                } else {
                    mostrarInformacion(this, "Estudiante no se encuentra registrado", "Error");
                    tblEstudianteEncontrado.setModel(borrarFilas(tblEstudianteEncontrado.getModel(), tblEstudianteEncontrado.getRowCount()));
                }
            } else {
                mostrarInformacion(this, "Solo se admiten numeros para buscar por cédula", "Error");
                txtCedulaBusqueda.setText("");
            }
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEliminarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEstudianteActionPerformed
        if (tblEstudianteEncontrado.getRowCount() > 0 || tblEstudiantes.getRowCount() > 0) {
            if (tblEstudianteEncontrado.getSelectedRow() != -1) {
                eliminarEstudiante(tblEstudianteEncontrado);
            } else if (tblEstudiantes.getSelectedRow() != -1) {
                eliminarEstudiante(tblEstudiantes);
            } else {
                mostrarInformacion(this, "Selecciona un estudiante", "Error");
            }
        } else {
            mostrarInformacion(this, "Tabla vacia", "Error");
        }
    }//GEN-LAST:event_btnEliminarEstudianteActionPerformed

    private void eliminarEstudiante(JTable tbl) {
        int respuesta = confirmarInformacion(this, "¿Seguro deseas eliminar el estudiante permanentemente?", "Eliminar estudiante");
        if (respuesta == SI) {
            control.eliminarEstudiante((Long) tbl.getValueAt(tbl.getSelectedRow(), 0));
            mostrarInformacion(this, "Estudiante eliminado correctamente", "Exito");
            cargarTablaEstudiantes();
        }
    }

    private void btnAnularMatriculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnularMatriculasActionPerformed
        if (tblEstudianteEncontrado.getRowCount() > 0 || tblEstudiantes.getRowCount() > 0) {
            if (tblEstudianteEncontrado.getSelectedRow() != -1 || tblEstudiantes.getSelectedRow() != -1) {
                int respuesta = confirmarInformacion(this, "¿Seguro deseas anular todas las matriculas?", "Anular matriculas");
                if (respuesta == SI) {
                    control.anularMatriculas(idAula);
                    mostrarInformacion(this, "Matriculas anuladas completamente", "Exito");
                    cargarTablaEstudiantes();
                }
            } else {
                mostrarInformacion(this, "Selecciona un estudiante", "Error");
            }
        } else {
            mostrarInformacion(this, "No hay estudiantes para anular matriculas", "Error");
        }
    }//GEN-LAST:event_btnAnularMatriculasActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        this.setVisible(false);
        principal.pnlPrincipalData.removeAll();
        principal.pnlPrincipalData.add(consultarEstudiantes);
        consultarEstudiantes.setVisible(true);
        consultarEstudiantes.cargarTablaCursos();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnVerEditarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerEditarEstudianteActionPerformed
        if (tblEstudianteEncontrado.getRowCount() > 0 || tblEstudiantes.getRowCount() > 0) {
            if (tblEstudianteEncontrado.getSelectedRow() != -1) {
                openFrameEditarEstudiante(tblEstudianteEncontrado);
            } else if (tblEstudiantes.getSelectedRow() != -1) {
                openFrameEditarEstudiante(tblEstudiantes);
            } else {
                mostrarInformacion(this, "Selecciona un estudiante", "Error");
            }
        } else {
            mostrarInformacion(this, "Tabla vacia", "Error");
        }
    }//GEN-LAST:event_btnVerEditarEstudianteActionPerformed

    private void tblEstudiantesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEstudiantesMouseClicked
        if (tblEstudianteEncontrado.getRowCount() > 0) {
            if (tblEstudianteEncontrado.getRowCount() != -1) {
                tblEstudianteEncontrado.clearSelection();
            }
        }
        if (evt.getClickCount() == 2) {
            openFrameEditarEstudiante(tblEstudiantes);
        }

    }//GEN-LAST:event_tblEstudiantesMouseClicked

    private void tblEstudianteEncontradoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEstudianteEncontradoMouseClicked
        if (tblEstudiantes.getRowCount() > 0) {
            if (tblEstudiantes.getRowCount() != -1) {
                tblEstudiantes.clearSelection();
            }
        }
        if (evt.getClickCount() == 2) {
            openFrameEditarEstudiante(tblEstudianteEncontrado);
        }
    }//GEN-LAST:event_tblEstudianteEncontradoMouseClicked

    public final void cargarEstadoMatricula() {
        for (Estudiante estudiante : control.obtenerListaEstudiantesAula(idAula)) {
            control.verificarEstadoMatricula(estudiante.getId());
        }
    }


    private void btnBuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseEntered
        btnBuscar.setBackground(new Color(78, 90, 126));
    }//GEN-LAST:event_btnBuscarMouseEntered

    private void btnBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseExited
        btnBuscar.setBackground(new Color(63, 72, 100));
    }//GEN-LAST:event_btnBuscarMouseExited

    private void jPanel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel6MouseEntered

    private void btnVerEditarEstudianteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerEditarEstudianteMouseExited
        btnVerEditarEstudiante.setBackground(new Color(63, 72, 100));
    }//GEN-LAST:event_btnVerEditarEstudianteMouseExited

    private void btnVerEditarEstudianteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerEditarEstudianteMouseEntered
        btnVerEditarEstudiante.setBackground(new Color(78, 90, 126));
    }//GEN-LAST:event_btnVerEditarEstudianteMouseEntered

    private void btnRegresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseEntered
        btnRegresar.setBackground(new Color(78, 90, 126));
    }//GEN-LAST:event_btnRegresarMouseEntered

    private void btnRegresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseExited
        btnRegresar.setBackground(new Color(63, 72, 100));
    }//GEN-LAST:event_btnRegresarMouseExited

    private void btnEliminarEstudianteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarEstudianteMouseEntered
        btnEliminarEstudiante.setBackground(new Color(201, 119, 119));
    }//GEN-LAST:event_btnEliminarEstudianteMouseEntered

    private void btnEliminarEstudianteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarEstudianteMouseExited
        btnEliminarEstudiante.setBackground(new Color(165, 80, 80));
    }//GEN-LAST:event_btnEliminarEstudianteMouseExited

    private void btnAnularMatriculasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnularMatriculasMouseEntered
        btnAnularMatriculas.setBackground(new Color(201, 119, 119));
    }//GEN-LAST:event_btnAnularMatriculasMouseEntered

    private void btnAnularMatriculasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnularMatriculasMouseExited
        btnAnularMatriculas.setBackground(new Color(165, 80, 80));
    }//GEN-LAST:event_btnAnularMatriculasMouseExited

    private void openFrameEditarEstudiante(JTable tbl) {
        verEditarEstudiante = new VerEditarEstudiante((Long) tbl.getValueAt(tbl.getSelectedRow(), 0), control, this);
        verEditarEstudiante.setVisible(true);
        verEditarEstudiante.setLocationRelativeTo(this);
        verEditarEstudiante.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    public final void cargarTablaEstudiantes() {
        tblEstudiantes.setModel(obtenerModeloTablaEstudiantesDetallado(new String[]{"CÉDULA", "NOMBRES", "EDAD", "ESTADO_MATRÍCULA"}, control.obtenerListaEstudiantesAula(idAula)));
        tblEstudiantes.setRowHeight(20);
    }

    private void cargarNombre() {
        lblAula.setText(control.leerAula(idAula).getNombre());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnularMatriculas;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminarEstudiante;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnVerEditarEstudiante;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAula;
    private javax.swing.JLabel lblMatricula2;
    private javax.swing.JTable tblEstudianteEncontrado;
    private javax.swing.JTable tblEstudiantes;
    private javax.swing.JTextField txtCedulaBusqueda;
    // End of variables declaration//GEN-END:variables

}
