package com.mycompany.gestion_alumnos.GUI;

import com.mycompany.gestion_alumnos.LOGICA.Controladora;
import com.mycompany.gestion_alumnos.LOGICA.Estudiante;
import java.awt.Color;
import javax.swing.JTable;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;

/**
 *
 * @author Frame-Code
 */
public class ListadoEstudiantesAnulados extends javax.swing.JPanel implements Mensajes, ModeloTabla {

    private Controladora control;
    private ConsultarEstudiantes consultarEstudiantes;
    private Principal principal;
    private VerEstudianteAnulado verAnulado;

    public ListadoEstudiantesAnulados() {
        initComponents();
    }

    public ListadoEstudiantesAnulados(Controladora control, ConsultarEstudiantes consultarEstudiantes, Principal principal) {
        this.control = control;
        this.consultarEstudiantes = consultarEstudiantes;
        this.principal = principal;
        this.initComponents();
        if (!control.leerListEstudiantes().isEmpty()) {
            this.cargarTablaEstudiantes();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEstudiantes = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        btnRegresar = new javax.swing.JButton();
        btnEliminarEstudiante = new javax.swing.JButton();
        btnEliminarTodos = new javax.swing.JButton();
        btnVerEditarEstudiante = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(196, 196, 196));
        setPreferredSize(new java.awt.Dimension(761, 657));

        jPanel1.setBackground(new java.awt.Color(196, 196, 196));
        jPanel1.setPreferredSize(new java.awt.Dimension(755, 657));

        jLabel17.setForeground(new java.awt.Color(99, 99, 99));
        jLabel17.setText("________________________________________________Todos los estudiantes_____________________________________________");

        jPanel5.setBackground(new java.awt.Color(180, 180, 180));

        tblEstudiantes.setBackground(new java.awt.Color(180, 180, 180));
        tblEstudiantes.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(23, 23, 23), 1, true));
        tblEstudiantes.setFont(new java.awt.Font("Waree", 0, 12)); // NOI18N
        tblEstudiantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {}
            },
            new String [] {

            }
        ));
        tblEstudiantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEstudiantesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblEstudiantes);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(180, 180, 180));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel6MouseEntered(evt);
            }
        });

        btnRegresar.setBackground(new java.awt.Color(63, 72, 100));
        btnRegresar.setFont(new java.awt.Font("Waree", 1, 12)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("<-- Regresar");
        btnRegresar.setBorder(null);
        btnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegresarMouseExited(evt);
            }
        });
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        btnEliminarEstudiante.setBackground(new java.awt.Color(165, 80, 80));
        btnEliminarEstudiante.setFont(new java.awt.Font("Waree", 1, 12)); // NOI18N
        btnEliminarEstudiante.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarEstudiante.setText("Eliminar estudiante");
        btnEliminarEstudiante.setBorder(null);
        btnEliminarEstudiante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEliminarEstudianteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminarEstudianteMouseExited(evt);
            }
        });
        btnEliminarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarEstudianteActionPerformed(evt);
            }
        });

        btnEliminarTodos.setBackground(new java.awt.Color(165, 80, 80));
        btnEliminarTodos.setFont(new java.awt.Font("Waree", 1, 12)); // NOI18N
        btnEliminarTodos.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarTodos.setText("Eliminar todos los estudiante");
        btnEliminarTodos.setBorder(null);
        btnEliminarTodos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEliminarTodosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminarTodosMouseExited(evt);
            }
        });
        btnEliminarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarTodosActionPerformed(evt);
            }
        });

        btnVerEditarEstudiante.setBackground(new java.awt.Color(63, 72, 100));
        btnVerEditarEstudiante.setFont(new java.awt.Font("Waree", 1, 12)); // NOI18N
        btnVerEditarEstudiante.setForeground(new java.awt.Color(255, 255, 255));
        btnVerEditarEstudiante.setText("Ver informacion detallada del estudiante ");
        btnVerEditarEstudiante.setBorder(null);
        btnVerEditarEstudiante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVerEditarEstudianteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVerEditarEstudianteMouseExited(evt);
            }
        });
        btnVerEditarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerEditarEstudianteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVerEditarEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEliminarTodos, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                    .addComponent(btnEliminarEstudiante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVerEditarEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Waree", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(23, 23, 23));
        jLabel2.setText("Consultar estudiantes con matricula anulada");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addComponent(jLabel17)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(2, 2, 2)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEstudianteActionPerformed
        if (tblEstudiantes.getRowCount() > 0) {
            if (tblEstudiantes.getSelectedRow() != -1) {
                eliminarEstudiante(tblEstudiantes);
            } else {
                mostrarInformacion(this, "Selecciona un estudiante", "Error");
            }
        } else {
            mostrarInformacion(this, "Tabla vacia", "Error");
        }
    }//GEN-LAST:event_btnEliminarEstudianteActionPerformed

    private void eliminarEstudiante(JTable tbl) {
        if (tblEstudiantes.getRowCount() > 0) {
            if (tblEstudiantes.getSelectedRow() != -1) {
                int respuesta = confirmarInformacion(this, "¿Seguro deseas eliminar el estudiante permanentemente?", "Eliminar estudiante");
                if (respuesta == SI) {
                    control.eliminarEstudianteAnulado((Long) tbl.getValueAt(tbl.getSelectedRow(), 0));
                    mostrarInformacion(this, "Estudiante eliminado correctamente", "Exito");
                    cargarTablaEstudiantes();
                }
            } else {
                mostrarInformacion(this, "Selecciona un estudiante", "Error");
            }
        } else {
            mostrarInformacion(this, "Tabla vacia", "Error");
        }
    }

    private void btnEliminarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarTodosActionPerformed
        if (tblEstudiantes.getRowCount() > 0) {
                int respuesta = confirmarInformacion(this, "¿Seguro deseas eliminar todos los estudiantes?", "Eliminar estudiantes");
                int nElementosTabla = tblEstudiantes.getRowCount();
                if (respuesta == SI) {
                    for (int i = 0; i < nElementosTabla; i++) {
                        control.eliminarEstudianteAnulado((Long) tblEstudiantes.getValueAt(i, 0));
                    }
                    mostrarInformacion(this, "Estudiantes eliminados correctamente", "Exito");
                    this.cargarTablaEstudiantes();
                }
        } else {
            mostrarInformacion(this, "Tabla vacia", "Error");
        }


    }//GEN-LAST:event_btnEliminarTodosActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        this.setVisible(false);
        principal.pnlPrincipalData.removeAll();
        principal.pnlPrincipalData.add(consultarEstudiantes);
        consultarEstudiantes.setVisible(true);
        consultarEstudiantes.cargarTablaCursos();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnVerEditarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerEditarEstudianteActionPerformed
        if (tblEstudiantes.getRowCount() > 0) {
            if (tblEstudiantes.getSelectedRow() != -1) {
                openFrameEditarEstudiante(tblEstudiantes);
            } else {
                mostrarInformacion(this, "Selecciona un estudiante", "Error");
            }
        } else {
            mostrarInformacion(this, "Tabla vacia", "Error");
        }
    }//GEN-LAST:event_btnVerEditarEstudianteActionPerformed

    private void tblEstudiantesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEstudiantesMouseClicked
        if (evt.getClickCount() == 2) {
            openFrameEditarEstudiante(tblEstudiantes);
        }

    }//GEN-LAST:event_tblEstudiantesMouseClicked


    private void jPanel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel6MouseEntered

    private void btnVerEditarEstudianteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerEditarEstudianteMouseExited
        btnVerEditarEstudiante.setBackground(new Color(63, 72, 100));
    }//GEN-LAST:event_btnVerEditarEstudianteMouseExited

    private void btnVerEditarEstudianteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerEditarEstudianteMouseEntered
        btnVerEditarEstudiante.setBackground(new Color(78, 90, 126));
    }//GEN-LAST:event_btnVerEditarEstudianteMouseEntered

    private void btnRegresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseEntered
        btnRegresar.setBackground(new Color(78, 90, 126));
    }//GEN-LAST:event_btnRegresarMouseEntered

    private void btnRegresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseExited
        btnRegresar.setBackground(new Color(63, 72, 100));
    }//GEN-LAST:event_btnRegresarMouseExited

    private void btnEliminarEstudianteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarEstudianteMouseEntered
        btnEliminarEstudiante.setBackground(new Color(201, 119, 119));
    }//GEN-LAST:event_btnEliminarEstudianteMouseEntered

    private void btnEliminarEstudianteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarEstudianteMouseExited
        btnEliminarEstudiante.setBackground(new Color(165, 80, 80));
    }//GEN-LAST:event_btnEliminarEstudianteMouseExited

    private void btnEliminarTodosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarTodosMouseEntered
        btnEliminarTodos.setBackground(new Color(201, 119, 119));
    }//GEN-LAST:event_btnEliminarTodosMouseEntered

    private void btnEliminarTodosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarTodosMouseExited
        btnEliminarTodos.setBackground(new Color(165, 80, 80));
    }//GEN-LAST:event_btnEliminarTodosMouseExited

    private void openFrameEditarEstudiante(JTable tbl) {
        verAnulado = new VerEstudianteAnulado((Long) tbl.getValueAt(tbl.getSelectedRow(), 0), control, this);
        verAnulado.setLocationRelativeTo(this);
        verAnulado.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    public final void cargarTablaEstudiantes() {
        tblEstudiantes.setModel(obtenerModeloTablaEstudiantes(new String[]{"CÉDULA", "NOMBRES", "EDAD", "ESTADO_MATRÍCULA"}, control.obtenerListaEstudiantesAnulados()));
        tblEstudiantes.setRowHeight(20);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarEstudiante;
    private javax.swing.JButton btnEliminarTodos;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnVerEditarEstudiante;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblEstudiantes;
    // End of variables declaration//GEN-END:variables

}
